version: "3.9"

services:
  model:
    build:
      context: .
      dockerfile: model/model.Dockerfile
    container_name: crypto-model
    restart: unless-stopped
    ports:
      - "8000:8000"

#  bot:
#    build:
#      context: .
#      dockerfile: bot/bot.Dockerfile
#    container_name: crypto-bot
#    restart: unless-stopped
#    depends_on:
#      - model
#    env_file:
#      - .env
#    restart: unless-stopped