"""adding new table for bot param and setup

Revision ID: 0110e6124bb7
Revises: cfbe9a66b878
Create Date: 2025-12-02 19:55:11.778547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0110e6124bb7'
down_revision: Union[str, Sequence[str], None] = 'cfbe9a66b878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botconfig',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bot_type', sa.String(length=50), nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_botconfig_bot_type'), 'botconfig', ['bot_type'], unique=False)
    op.create_index(op.f('ix_botconfig_key'), 'botconfig', ['key'], unique=False)
    op.alter_column('decision', 'bot_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('decision', 'outcome_pnl_usdt',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('decision', 'outcome_pnl_pct',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('decision', 'outcome_equity_delta',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('decision', 'outcome_label',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_decision_bot_type'), 'decision', ['bot_type'], unique=False)
    op.create_index(op.f('ix_decision_outcome_label'), 'decision', ['outcome_label'], unique=False)
    op.alter_column('trade', 'bot_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_trade_bot_type'), 'trade', ['bot_type'], unique=False)

    botconfig_table = sa.table(
        "botconfig",
        sa.Column("bot_type", sa.String(length=50)),
        sa.Column("key", sa.String(length=100)),
        sa.Column("value", sa.String(length=255)),
    )

    op.bulk_insert(
        botconfig_table,
        [
            # core behavior
            {"bot_type": "foundational", "key": "min_confidence", "value": "0.51"},
            {"bot_type": "foundational", "key": "sleep_seconds", "value": "30"},

            # TP/SL thresholds
            {"bot_type": "foundational", "key": "tp_pct", "value": "0.003"},
            {"bot_type": "foundational", "key": "sl_pct", "value": "-0.004"},

            # same-candle decision / logging thresholds
            {
                "bot_type": "foundational",
                "key": "drastic_move_threshold",
                "value": "0.0005",
            },
            {
                "bot_type": "foundational",
                "key": "hold_conf_margin",
                "value": "0.10",
            },
            {
                "bot_type": "foundational",
                "key": "hold_sample_every_min",
                "value": "10",
            },

            # per-symbol min trade amount
            {
                "bot_type": "foundational",
                "key": "min_trade_amount.BTC/USDT",
                "value": "0.00001",
            },
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_bot_type'), table_name='trade')
    op.alter_column('trade', 'bot_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_decision_outcome_label'), table_name='decision')
    op.drop_index(op.f('ix_decision_bot_type'), table_name='decision')
    op.alter_column('decision', 'outcome_label',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('decision', 'outcome_equity_delta',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('decision', 'outcome_pnl_pct',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('decision', 'outcome_pnl_usdt',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('decision', 'bot_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_botconfig_key'), table_name='botconfig')
    op.drop_index(op.f('ix_botconfig_bot_type'), table_name='botconfig')
    op.drop_table('botconfig')
    # ### end Alembic commands ###
