"""adding new fields to decisions

Revision ID: 57f3a1205080
Revises: d06f4b116dd2
Create Date: 2025-12-01 09:00:31.371306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57f3a1205080'
down_revision: Union[str, Sequence[str], None] = 'd06f4b116dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision', sa.Column('outcome_pnl_usdt', sa.Float(), nullable=True))
    op.add_column('decision', sa.Column('outcome_pnl_pct', sa.Float(), nullable=True))
    op.add_column('decision', sa.Column('outcome_equity_delta', sa.Float(), nullable=True))
    op.add_column('decision', sa.Column('outcome_label', sa.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('decision', 'bot_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_decision_bot_type'), 'decision', ['bot_type'], unique=False)
    op.create_index(op.f('ix_decision_outcome_label'), 'decision', ['outcome_label'], unique=False)
    op.alter_column('trade', 'bot_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_trade_bot_type'), 'trade', ['bot_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_bot_type'), table_name='trade')
    op.alter_column('trade', 'bot_type',
               existing_type=sa.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_decision_outcome_label'), table_name='decision')
    op.drop_index(op.f('ix_decision_bot_type'), table_name='decision')
    op.alter_column('decision', 'bot_type',
               existing_type=sa.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('decision', 'outcome_label')
    op.drop_column('decision', 'outcome_equity_delta')
    op.drop_column('decision', 'outcome_pnl_pct')
    op.drop_column('decision', 'outcome_pnl_usdt')
    # ### end Alembic commands ###
